
main: 
	g++ main.cpp Stepper/AccelStepper.cpp Tools/Tools.cpp Communication/Network.cpp Communication/Tcp.cpp Communication/Udp.cpp Communication/Frame.cpp \
	-o main -lpthread -lwiringPi
	
clean:
	rm -rf *.o main

